CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create a new table if it doesn't exist
CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL
        CHECK (char_length(title) < 51 AND char_length(title)>5 ),
    location TEXT NOT NULL
        CHECK (char_length(location) < 51 AND char_length(location)>5),
    image TEXT NOT NULL
        CHECK (image ~ '^https?://' AND image ~ '\.(png|jpg|jpeg|gif|gifv)$'),
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Alter if it already exists (make changes to the DB constraints here)
ALTER TABLE IF EXISTS events
    DROP CONSTRAINT IF EXISTS title,
    ADD  CONSTRAINT title CHECK (char_length(title) < 50 AND char_length(title)>5 ), 
    DROP CONSTRAINT IF EXISTS location,
    ADD  CONSTRAINT location CHECK (char_length(location) < 50 AND char_length(location)>5),
    DROP CONSTRAINT IF EXISTS image, 
    ADD  CONSTRAINT image CHECK (image ~ '^https?://' AND image ~ '\.(png|jpg|jpeg|gif|gifv)$');


CREATE TABLE IF NOT EXISTS rsvp (
    event_id INT REFERENCES events(id),
    email_address TEXT NOT NULL
        CHECK (email_address ~ '^[a-zA-Z0-9_\-\.]+@yale\.edu$'),
    confirmation_code text GENERATED ALWAYS AS (encode(digest(email_address,'sha256')::bytea,'hex')) STORED,
    CONSTRAINT unique_rsvp PRIMARY KEY (event_id, email_address)
);

ALTER TABLE IF EXISTS rsvp
    DROP CONSTRAINT IF EXISTS email_address,
    ADD CONSTRAINT email_address CHECK (email_address ~ '^[a-zA-Z0-9_\-\.]+@yale\.edu$');
        
-- "Upsert" our default events. This will overwrite your
-- default events every time this code is run.
INSERT INTO events (id, date, image, title, location) VALUES
('1', '2022-10-17 16:30:00', 'http://i.imgur.com/pXjrQ.gif', 'SOM House Party', 'Kyle''s house'),
('2', '2022-10-19 19:00:00', 'http://i.imgur.com/7pe2k.gif', 'BBQ party for hackers and nerds', 'Sharon Oster''s house'),
('3', '2022-12-02 18:00:00', 'http://i.imgur.com/CJLrRqh.gif', 'BBQ for managers', 'Barry Nalebuff''s house'),
('4', '2022-12-21 19:00:00', 'http://i.imgur.com/02KT9.gif', 'Cooking lessons for the busy business student', 'Yale Farm')
ON CONFLICT ON CONSTRAINT events_pkey DO UPDATE
SET (id, date, image, title, location) = (EXCLUDED.id, EXCLUDED.date, EXCLUDED.image, EXCLUDED.title, EXCLUDED.location) ;

-- Notice that I did not insert an event with id 2. This is
-- just so you see that not all ids will be present.

-- Reset the id sequence because we did some manual insertions.
SELECT setval('events_id_seq', (SELECT MAX(id)+1 FROM events));

INSERT INTO rsvp (event_id, email_address) VALUES
('1', 'kim.kardashian@yale.edu'),
('2', 'kim.kardashian@yale.edu'),
('3', 'kim.kardashian@yale.edu'),
('4', 'kim.kardashian@yale.edu'),
('1', 'kyle.jensen@yale.edu'),
('2', 'kyle.jensen@yale.edu'),
('3', 'kyle.jensen@yale.edu'),
('4', 'kyle.jensen@yale.edu')

ON CONFLICT ON CONSTRAINT unique_rsvp DO UPDATE --Excludes running this if the RSVP table already has the above values
SET (event_id, email_address) = (EXCLUDED.event_id, EXCLUDED.email_address) 
